services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=ROW
      - --binlog-row-image=FULL
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  api:
    build: ./api
    container_name: api
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: appdb
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  client:
    build: ./client
    container_name: client
    ports:
      - "8080:80"
    depends_on:
      - api
  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: quay.io/debezium/kafka:2.7
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181

  connect:
    image: quay.io/debezium/connect:2.7
    container_name: connect
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - mysql
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - kafka
      - connect
    environment:
      KAFKA_BROKER: kafka:9092
  
  connector-init:
    image: curlimages/curl:latest
    container_name: connector-init
    depends_on:
      - connect
    volumes:
      - ./connector:/config
    entrypoint: ["sh", "/config/register.sh"]
    restart: "no"